# Generated by Django 6.0.3 on 2026-04-10 08:40

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('problems', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestCase',
            fields=[
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ('input_data', models.TextField()),
                ('expected_output', models.TextField()),
                ('is_hidden', models.BooleanField(default=False)),
                (
                    'problem',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='test_cases',
                        to='problems.problem',
                    ),
                ),
            ],
        ),
    ]
