# Generated by Django 6.0.3 on 2026-03-18 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='status',
            field=models.CharField(choices=[('done', 'Done'), ('wrong_answer', 'Wrong answer'), ('pending', 'Pending'), ('error', 'Error')], default='pending', max_length=15),
        ),
    ]
