# Generated by Django 6.0.3 on 2026-04-10 08:40

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Problem',
            fields=[
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                (
                    'difficulty',
                    models.CharField(
                        choices=[
                            ('easy', 'easy'),
                            ('medium', 'medium'),
                            ('hard', 'hard'),
                        ],
                        default='easy',
                        max_length=10,
                    ),
                ),
                ('category', models.CharField(max_length=200)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
