# Generated by Django 6.0.3 on 2026-04-03 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
